version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: 12.17.0
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test:
    jobs:
      - test